# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: africandev
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: user-service
# "service" is the name of this project. This will also be added to your AWS resource names.
service: user-service

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: true
  stage: "dev"
  region: "us-east-1"
  httpApi:
    cors: true
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
    DB_PORT: ${env:DB_PORT}
    JWT_SECRET: ${env:JWT_SECRET}
    TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID}
    TWILIO_AUTH_TOKEN: ${env:TWILIO_AUTH_TOKEN}
    TWILIO_PHONE_NUMBER: ${env:TWILIO_PHONE_NUMBER}

functions:
  signup:
    handler: dist/handler.Signup
    events:
      - httpApi:
          path: /signup
          method: post
  login:
    handler: dist/handler.Login
    events:
      - httpApi:
          path: /login
          method: post

  verify:
    handler: dist/handler.Verify
    events:
      - httpApi:
          path: /verify
          method: get
      - httpApi:
          path: /verify
          method: post

  profile:
    handler: dist/handler.Profile
    events:
      - httpApi:
           path: /profile
           method: get
      - httpApi:
           path: /profile
           method: put
      - httpApi:
           path: /profile
           method: post

  cart:
    handler: dist/handler.Cart
    events:
      - httpApi:
           path: /cart
           method: get
      - httpApi:
           path: /cart
           method: post
      - httpApi:
            path: /cart
            method: delete

  payment: 
    handler: dist/handler.Payment
    events:
      - httpApi:
           path: /payment
           method: get
      - httpApi:
           path: /payment
           method: post
      - httpApi:
            path: /payment
            method: put


plugins:
  - serverless-offline
  - '@jimdo/serverless-dotenv'

package:
  exclude:
    - .gitignore
    - .git/**

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - 'aws-sdk'
    target: node18
    define:
      __DEV__: false
    platform: node
    concurrency: 10